apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-platform
  namespace: devops-toolchain
spec:
  project: default
  source:
    repoURL: https://gitea.devops.cicd.test/admin/devops-platform-deploy.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
